# Generated by Django 5.1.3 on 2024-11-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimoni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="testimoni",
            name="nama_pekerja",
        ),
        migrations.RemoveField(
            model_name="testimoni",
            name="sesi_layanan",
        ),
        migrations.AlterField(
            model_name="testimoni",
            name="subkategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testimoni.subcategory"
            ),
        ),
    ]
