# Generated by Django 5.1.3 on 2024-11-18 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_worker_testimoni"),
        ("testimoni", "0002_subcategory_remove_testimoni_nama_pekerja_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimoni",
            name="subkategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimoni_testimonials",
                to="main.subcategory",
            ),
        ),
        migrations.RenameField(
            model_name="testimoni",
            old_name="komentar",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="testimoni",
            name="tanggal",
        ),
        migrations.AddField(
            model_name="testimoni",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimoni",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimoni_testimonials",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testimoni",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimoni_workers",
                        to="main.subcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testimoni",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimoni_testimonials",
                to="testimoni.worker",
            ),
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
